COPYRIGHT
=> Adds Copyright file similar to other pulp org ones

.github/workflows/cron.yml
Make cron job run every 2 hours to get more feedback
Reference: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
=> Declaring env vars from secrets

.github/workflows/cron.yml
build failed due .gem directory didn't exist
[noissue]
=> Installing ruby

.github/workflows/cron.yml, setup.py
=> Install httpie

.github/publish_client_gem.sh, .github/publish_client_pypi.sh, .github/workflows/cron.yml
=> Getting django running during deploy

.github/workflows/cron.yml
set HTTPIE_CONFIG_DIR
[noissue]
=> Include after failure to get more feedback

.github/publish_client_pypi.sh, .github/publish_plugin_pypi.sh, .github/workflows/cron.yml
=> Updating pip and installing wheels

.github/workflows/cron.yml
=> Deploy needs entire bindings workflow

.github/publish_client_gem.sh, .github/workflows/cron.yml
=> Building before credentials

.github/publish_client_gem.sh
=> Fix ruby script

CHANGES/6004.feature, pulp_npm/app/tasks/synchronizing.py, pulp_npm/app/webserver_snippets/apache.conf, pulp_npm/app/webserver_snippets/nginx.conf
https://pulp.plan.io/issues/6004
closes #6004
=> Download a package with its dependencies

MANIFEST.in
=> Include MANIFEST.in

.github/install.sh, .github/workflows/ci.yml, .github/workflows/cron.yml, template_config.yml
=> Introduce S3 testing

.github/workflows/ci.yml, .github/workflows/cron.yml
=> Fix release on tags

.github/workflows/cron.yml
=> Add missing variable on CI

.github/install.sh, .github/workflows/ci.yml, pulp_npm/app/viewsets.py
Required PR: https://github.com/pulp/pulpcore/pull/785
[noissue]
=> OpenAPI v3 with drf-spectacular

.bumpversion.cfg, CHANGES.rst, CHANGES/6004.feature, docs/_static/api.json, docs/workflows/sync.rst, pulp_npm/__init__.py, requirements.txt, setup.py
I did some test and I noticed it  would break the sphinx on the first release
=> Release 0.1.0a1

.github/workflows/nightly.yml
=> Set TEST on nightly job

.github/workflows/nightly.yml
=> Run nightly every 5 minutes for testing purposes

.ci/scripts/release.py, .github/workflows/nightly.yml, .github/workflows/scripts/install.sh, .github/workflows/scripts/script.sh
=> Fix the nightly job

.github/workflows/nightly.yml
=> Fix TEST env

.github/workflows/nightly.yml
=> Set matrix TEST variable

.github/workflows/nightly.yml
=> Add in missing secrets

.ci/scripts/publish_client_gem.sh, .github/workflows/nightly.yml
=> Create the .gem directory

.github/workflows/nightly.yml
=> Install wheel

.github/workflows/nightly.yml
=> Fix publish nightly docs

.github/workflows/nightly.yml
=> Replace docs script

.github/workflows/publish_docs.yml
=> Fix publish_docs path

.github/workflows/nightly.yml
=> Back to nightly

.bumpversion.cfg, .ci/scripts/release.py, CHANGES.rst, pulp_npm/__init__.py, requirements.txt, setup.py
```
python .ci/scripts/release.py patch --lower 3.7 --upper 3.10
```
release script needed a fix
=> Release 0.1.0a2

.ci/scripts/publish_docs.sh, .github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
=> Update github files

.ci/scripts/publish_docs.sh
=> Fix publish docs

.github/workflows/nightly.yml
This reverts commit bbc8f3b4f14c37fdea1b2e6335312680e78787b1.
[noissue]
=> Revert "Change frequency of nightly for testing"

.github/workflows/nightly.yml
=> Fix secrets

.ci/scripts/secrets.py, .github/workflows/nightly.yml
=> Set secrets automatically

.github/workflows/fips.yml
=> Updating FIPS workflow

.github/workflows/fips.yml
=> Disable https on FIPS test

.ci/scripts/publish_client_gem.sh, .ci/scripts/publish_client_pypi.sh, .github/workflows/fips.yml, .github/workflows/scripts/utils.sh, template_config.yml
=> Updating CI

.github/workflows/ci.yml, .github/workflows/dispatch.yml
=> Fix disparch job

.github/workflows/release.yml
=> Test release dispatch

.github/workflows/release.yml
=> Allow the release process to be retriggered

.ci/scripts/publish_plugin_pypi.sh, .github/workflows/release.yml
=> Tweaks to release workflow

.ci/scripts/publish_plugin_pypi.sh
=> Testing publish pypi job with more output

.github/workflows/release.yml
=> Update ci scripts before running them

.github/workflows/release.yml
=> One more CI fix

CHANGES/8574.bugfix, pulp_npm/app/webserver_snippets/apache.conf
https://pulp.plan.io/issues/8574
fixes: #8574
=> Fix apache snippet

.ci/scripts/publish_client_gem.sh, .ci/scripts/publish_client_pypi.sh, .ci/scripts/publish_plugin_pypi.sh
=> Fix publish job

pulp_npm/app/viewsets.py
=> Use dispatch instead of enqueue_with_reservation

.ci/ansible/Containerfile.j2, .github/workflows/scripts/script.sh, requirements.txt, setup.py
=> Drop support for Python 3.6 and 3.7

.github/workflows/update_ci.yml
=> Fix update job

.github/workflows/update_ci.yml
=> Fix update ci workflow by using RELEASE_TOKEN

.github/workflows/update_ci.yml
=> Use secrets on update job

.github/workflows/update_ci.yml
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
[noissue]
=> Adding permissions to update job

.github/workflows/update_ci.yml
=> Use NPM_GITHUB_TOKEN

.github/workflows/scripts/before_install.sh, template_config.yml
=> Activate check that tasking is async safe wrt ORM

.ci/ansible/Containerfile.j2
=> Use Github Container Registry

.github/workflows/update_ci.yml
=> Update multiple branches

.github/workflows/update_ci.yml
=> Improve the update workflow

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, template_config.yml
=> Publish pulp_npm docs

.github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/scripts/install_python_client.sh, .github/workflows/scripts/publish_docs.sh
=> Improve bindings docs publication

.github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/scripts/publish_docs.sh
=> Fix bindings docs

pulp_npm/app/tasks/synchronizing.py
=> Fix DeclarativeArtifact

.github/workflows/kanban.yml
=> Kanban PoC

.github/workflows/kanban.yml
=> fix "Expected stream end parse event"

.github/workflows/kanban.yml
=> Fixing kanban workflow

.github/workflows/kanban.yml
=> fix kanban

.github/workflows/kanban.yml
=> kanban with pulpbot user

.github/workflows/kanban.yml
=> debug kanban

.github/workflows/kanban.yml
=> Revert "debug kanban"

.github/workflows/kanban.yml
=> Revert "kanban"

.github/workflows/kanban.yml
=> linked issues

.github/workflows/kanban.yml
=> Remove debugging

.github/workflows/kanban.yml
=> Finish kanban test

.github/workflows/kanban.yml
=> Update kanban action

.github/workflows/kanban.yml
=> Adding org

.github/workflows/kanban.yml
=> Revert "Adding org"

CHANGES/275.bugfix, pulp_npm/app/viewsets.py, pulp_npm/tests/functional/api/test_sync.py
=> Fixes a sync operation demanding the remote URL when the repository already have one.

CHANGES/278.feature, pulp_npm/app/models.py, pulp_npm/app/serializers.py, pulp_npm/app/utils.py, pulp_npm/tests/functional/api/test_download_content.py, pulp_npm/tests/functional/api/test_pull_through_caching.py
=> Pull-through cache feature.

docs/user/guides/_SUMMARY.md, docs/user/guides/sync.md
=> Fixes the docs and add the pull-through_cache docs.

CHANGES/298.doc, docs/user/guides/sync.md
Thanks @git-hyagi for point it out.
Closes #298 
Co-authored-by: @git-hyagi
=> Fixes the docs to show the domain usage on the example endpoints.

CHANGES/299.feature, pulp_npm/app/models.py, pyproject.toml
=> Enable adding pull-through content to associated repositories.

CHANGES/315.bugfix, pulp_npm/app/models.py, pulp_npm/app/tasks/synchronizing.py, pulp_npm/app/utils.py, pulp_npm/tests/functional/api/test_download_content.py
=> Fixes how package names are stored.
